name: ai_weather
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^17.0.1
  geolocator: ^14.0.2
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  flutter_dotenv: ^6.0.0
  connectivity_plus: ^7.0.0
  pretty_dio_logger: ^1.4.0
  dio: ^5.9.0
  retrofit: ^4.9.1
  http: ^1.6.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3  
  path_provider: ^2.1.5
  intl: ^0.20.2
  logger: ^2.6.2
  collection: ^1.19.1
  skeletonizer: ^2.1.2
  app_settings: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.10.4
  freezed: ^3.2.3
  retrofit_generator: ^10.2.0
  json_serializable: ^6.11.2
  riverpod_generator: ^3.0.3




flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/



