name: ai_weather
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  geolocator: ^14.0.2

  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

  flutter_dotenv: ^6.0.0

  dio: ^5.9.0
  retrofit: ^4.9.1
  
  freezed_annotation: ^3.1.0

  json_annotation: ^4.9.0

  shared_preferences: ^2.5.3
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3
  path_provider: ^2.1.5

  intl: ^0.20.2

  logger: ^2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.10.4

  freezed: ^3.2.3

  retrofit_generator: ^10.2.0

  json_serializable: ^6.11.2

  riverpod_generator: ^3.0.3

  pretty_dio_logger: ^1.4.0

  hive_ce_generator: ^1.10.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/



